[build]

publish = "docs/.vuepress/dist"
command = "yarn docs:build"

[[redirects]]
from = "http://logb.netlify.com/*"
to = "https://logb.hu/:splat"
status = 302
force = true

[[redirects]]
from = "https://logb.netlify.com/*"
to = "https://logb.hu"
status = 302
force = true

[[redirects]]
from = "https://logb.netlify.com"
to = "https://logb.hu"
status = 302
force = true

[[redirects]]
from = "http://logb.netlify.com"
to = "https://logb.hu"
status = 302
force = true

[[redirects]]
from = "http://www.logb.hu/*"
to = "https://logb.hu/:splat"
status = 302
force = true

[[redirects]]
from = "https://www.logb.hu/*"
to = "https://logb.hu"
status = 302
force = true

[[redirects]]
from = "https://www.logb.hu"
to = "https://logb.hu"
status = 302
force = true

[[redirects]]
from = "http://www.logb.hu"
to = "https://logb.hu"
status = 302
force = true