[build]

publish = "docs/.vuepress/dist"
command = "yarn docs:build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "*vibrant-pike-4dd77d.netlify.com/*"
to = "https://logb.hu/:splat"
status = 302
force = true
